### ISSUE TITLE
Refactor: Improve test coverage

### ISSUE THREAD

**Issue by provinzkraut** [litestar-org/litestar#880] opened 2022-11-29 16:32 UTC
There are currently some things that need test coverage: https://sonarcloud.io/component_measures?id=starlite-api_starlite&metric=new_coverage&view=list

This isn't something that needs to be addressed in a single PR, but we should keep it on the radar and make incremental improvements.

<a href="https://polar.sh/litestar-org/litestar/issues/880">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/880/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/880/pledge.svg">
</picture>
</a>

**Comment by Goldziher** [comment] 2022-12-01 17:57
duplicate of #406

**Closed** 2023-09-09 06:37 UTC
Labels: help wanted, tests-issue
