### ISSUE TITLE
Bug: Validation Exception for required headers during CORS pre-flight request

### ISSUE THREAD

**Issue by abdulhaq-e** [litestar-org/litestar#2739] opened 2023-11-23 08:01 UTC
### Description

CORS pre-flight "OPTIONS" request doesn't include the headers that are attached to the actual request. This causes a validation exception when the litestar handler has a required header.

### MCVE

```python
# Your MCVE code here
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

latest

### Platform

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2739">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2739/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2739/pledge.svg">
</picture>
</a>

**Comment by abdulhaq-e** [comment] 2023-11-23 08:03
here is one possible solution that worked for me. Changing the function at https://github.com/litestar-org/litestar/blob/main/litestar/_kwargs/extractors.py#L56 to be:
```python
def _create_param_mappings(
    expected_params: set[ParameterDefinition], connection: ASGIConnection
) -> ParamMappings:
    alias_and_key_tuples = []
    alias_defaults = {}
    alias_to_params: dict[str, ParameterDefinition] = {}
    for param in expected_params:
        alias = param.field_alias
        if param.param_type == ParamType.HEADER:
            alias = alias.lower()

        alias_and_key_tuples.append((alias, param.field_name))

        if not (param.is_required or param.default is Ellipsis):
            alias_defaults[alias] = param.default
        elif (
            connection.scope.get("method") == "OPTIONS"
            and param.param_type == ParamType.HEADER
            and param.is_required
        ):
            alias_defaults[alias] = None

        alias_to_params[alias] = param

    return ParamMappings(
        alias_and_key_tuples=alias_and_key_tuples,
        alias_defaults=alias_defaults,
        alias_to_param=alias_to_params,
    )
```

what do you think

**Comment by peterschutt** [comment] 2023-11-23 22:35
It would make it easier to review your suggestion if you could add an MCVE to the OP @abdulhaq-e, or open a PR for your implementation with a test.

**Comment by provinzkraut** [comment] 2023-11-28 13:26
Closing this as not a bug. The behaviour is expected and any workarounds will lead to more undesired behaviour. See #2755 for a discussion of this topic

**Closed by provinzkraut** 2023-11-28 13:26 UTC
Labels: bug
