### ISSUE TITLE
Bug: Installing SQLAlchemy via LiteStar doesn't install required dependency Greenlet

### ISSUE THREAD

**Issue by AgarwalPragy** [litestar-org/litestar#2568] opened 2023-10-30 23:28 UTC
### Description

Greenlet is a required dependency for SQLAlchemy: https://github.com/sqlalchemy/sqlalchemy/blob/6ba7499cdef168c9b8def2f160d3a2f09fc83218/setup.cfg#L40

Installing SQLAlchemy with Asyncio (`pip install 'sqlalchemy[asyncio]`) installs Greenlet automatically.

However, when SQLAlchemy is installed via Litestar `pip install 'litestar[standard,sqlalchemy]'`, it misses out Greenlet

### Steps to reproduce

Installing SQLAlchemy via Litestar

```sh
rm -rf litestar-install-test
mkdir litestar-install-test
cd litestar-install-test
python3 -m venv venv
source venv/bin/activate
pip install 'litestar[standard,sqlalchemy]'
pip freeze | grep -i sqlalchemy
pip freeze | grep -i greenlet
```

output
```
SQLAlchemy==2.0.22
# note that no greenlet is installed
```

-- --

Installing SQLAlchemy on its own

```sh
rm -rf litestar-install-test
mkdir litestar-install-test
cd litestar-install-test
python3 -m venv venv
source venv/bin/activate
pip install 'litestar[standard]' 'sqlalchemy[asyncio]'
pip freeze | grep -i sqlalchemy
pip freeze | grep -i greenlet
```

output
```
SQLAlchemy==2.0.22
greenlet==3.0.1
```

### Litestar Version

litestar==2.2.1

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2568">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2568/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2568/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment] 2023-10-31 00:57
I checked this yesterday on my Linux build and confirmed it does install greenlet.

It looks like this is platform related: https://github.com/sqlalchemy/sqlalchemy/issues/7714

I suppose we should add greenlet to our sqlalchemy extra then, or make it `sqlalchemy[asyncio]`.

**Comment by cofin** [comment] 2023-10-31 01:06
@peterschutt @AgarwalPragy This is how we address this in the fullstack repository.

```ini
  "greenlet; sys_platform == \"darwin\"",
```

Perhaps I need to just add this to the `advanced-alchemy` dependencies.

**Comment by cofin** [comment] 2023-10-31 01:15
Fixed by https://github.com/jolt-org/advanced-alchemy/pull/84

**Comment by peterschutt** [comment] 2023-10-31 01:24
Closed as fixed upstream.

**Closed by peterschutt** 2023-10-31 01:24 UTC
Labels: bug, dependencies
