### ISSUE TITLE
Bug: Using DTOData with the codegen backend decodes data incorrectly

### ISSUE THREAD

**Issue by abdulhaq-e** [litestar-org/litestar#3679] opened 2024-08-20 20:28 UTC
### Description

I had some code working before upgrading litestar. The newer versions where the codegen backend is enabled by default broke some tests. Here I'm copying the code in the doc and making small adjustments to match my case, I'm assuming it will behave the same, didn't try it yet.

```python
from __future__ import annotations

from dataclasses import dataclass, field
from uuid import UUID, uuid4

from litestar import Litestar, post
from litestar.dto import DataclassDTO, DTOConfig

@dataclass
class User:
    name: str
    email: str
    age: int
    id: UUID = field(default_factory=uuid4)
    nested_1: NestedUserAttr
  
@dataclass
class NestedUserAttr:
    key: int
    nested_2: AnotherNestedUserAttr

@dataclass
class AnotherNestedUserAttr:
    a_nested_key: int | None = None


class UserWriteDTO(DataclassDTO[User]):
    """Don't allow client to set the id."""
    config = DTOConfig(exclude={"id"},  max_nested_depth=4)

@post("/users", dto=UserWriteDTO, return_dto=None, sync_to_thread=False)

def create_user(data: DTOData[User]) -> User:
    """Create an user."""
    d = data.create_instance()
    return d

app = Litestar(route_handlers=[create_user])
```

Here is the issue: sending a proper json encoded data to the endpoint would result in `a_nested_key = None`.  I'm not yet sure is it because of a) the default value b) the depth of nesting.

The behaviour isn't the same with `experimental_codegen_backend=False`.

### MCVE

```python
# Your MCVE code here
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

main branch

### Platform

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3679">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3679/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3679/pledge.svg">
</picture>
</a>

**Comment by Alc-Alc** [comment] 2024-08-21 01:27
I don't think I can see any difference, can you check this

**Comment by IvanovCosmin** [comment] 2024-09-09 20:03
I did not manage to reporduce this issue.
This is my unit test, which passes with the latest version of the code.
Please let me know if I misunderstood the issue, and if it still reproduces with latest.

```python
def test_dtodata_with_codegen_decodes_data_correctly() -> None:
    from litestar import post
    from litestar.dto import DataclassDTO, DTOConfig


    class UserWriteDTO(DataclassDTO[NestedModel]):
        """Don't allow client to set the id."""
        config = DTOConfig(max_nested_depth=4, experimental_codegen_backend=True)

    @post("/users", dto=UserWriteDTO, return_dto=None, sync_to_thread=False)
    def create_user(data: DTOData[NestedModel]) -> NestedModel:
        """Create an user."""
        d: NestedModel = data.create_instance()
        return d
    
    with create_test_client(route_handlers=[create_user]) as client:
        res = client.post("/users", json={
            "a": {
                "b" : {
                    "c": 10
                }
            }
        }).json()

        assert res['a']['b']['c'] == 10
```

**Comment by provinzkraut** [comment] 2024-09-10 15:58
@abdulhaq-e I also can't reproduce this. Closing this for now.

**Closed by provinzkraut** 2024-09-10 15:58 UTC
Labels: Bug :bug:
