### ISSUE TITLE
Enhancement: litestar.types.ExceptionHandler

### ISSUE THREAD

**Issue by Murtagy** [litestar-org/litestar#3613] opened 2024-07-08 08:42 UTC
### Summary

Shouldn't the ExceptionHandler accept asynchronous functions, same as in most other places where both sync and async callables are allowed?

### Basic Example

Right now I do simple error reports to my messenger. 
I could have used the async code to do that.

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3613">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3613/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3613/pledge.svg">
</picture>
</a>

**Comment by Murtagy** [comment] 2024-07-08 08:44
If there is agreement on that it makes sense - I may try implementing the change

**Comment by Alc-Alc** [comment] 2024-07-08 09:54
Closing as duplicate of https://github.com/litestar-org/litestar/issues/2262. Feel free to reopen if its not 🙂

**Closed by Alc-Alc** 2024-07-08 09:54 UTC
Labels: Enhancement
