### ISSUE TITLE
Bug: Uploading list of files via an object fails validation if there's only a single file

### ISSUE THREAD

**Issue by guacs** [litestar-org/litestar#2939] opened 2024-01-03 04:29 UTC
### Description

If there's some model like the one below and only one file is provided by the client, then the validation fails.

```python
class FileModel(Struct):
    files: list[UploadFile]
```

This is the same issue as in #2753. That PR, unfortunately, only handled this scenario for `data: list[FileUpload]` defined directly on the handlers. We'll have to go through all the fields of the `FieldDefinition` and do that same check that was introduced in that PR. I don't think this has to be done recursively though since complex objects aren't supported.

### MCVE

```python
from __future__ import annotations

from msgspec import Struct

from litestar import post
from litestar.datastructures import UploadFile
from litestar.enums import RequestEncodingType
from litestar.params import Body
from litestar.status_codes import HTTP_201_CREATED
from litestar.testing.helpers import create_test_client


class FileUpload(Struct):
    files: list[UploadFile]


@post(path="/")
async def upload_files_object(data: FileUpload = Body(media_type=RequestEncodingType.MULTI_PART)) -> list[str]:
    return [f.filename for f in data.files]


with create_test_client([upload_files_object], debug=True) as client:
    # Works if more than 1 file is provided.
    # files = [("files", b"1"), ("files", b"2")]

    # Fails if only 1 file is provided.
    files = [("files", b"1")]
    response = client.post("/", files=files)
```

### Steps to reproduce

```bash
1. Run the MCVE
```

### Logs

```bash
Traceback (most recent call last):
  File "/home/guacs/open-source/litestar/litestar/_signature/model.py", line 189, in parse_values_from_connection_kwargs
    return convert(kwargs, cls, strict=False, dec_hook=deserializer, str_keys=True).to_dict()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
msgspec.ValidationError: Expected `array`, got `UploadFile` - at `$.data.files`

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/guacs/open-source/litestar/litestar/middleware/exceptions/middleware.py", line 191, in __call__
    await self.app(scope, receive, send)
  File "/home/guacs/open-source/litestar/litestar/routes/http.py", line 82, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guacs/open-source/litestar/litestar/routes/http.py", line 134, in _get_response_for_request
    return await self._call_handler_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guacs/open-source/litestar/litestar/routes/http.py", line 154, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guacs/open-source/litestar/litestar/routes/http.py", line 193, in _get_response_data
    parsed_kwargs = route_handler.signature_model.parse_values_from_connection_kwargs(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guacs/open-source/litestar/litestar/_signature/model.py", line 202, in parse_values_from_connection_kwargs
    raise cls._create_exception(messages=messages, connection=connection) from e
litestar.exceptions.http_exceptions.ValidationException: 400: Validation failed for POST http://testserver.local/
Traceback (most recent call last):
  File "/home/guacs/open-source/litestar/litestar/_signature/model.py", line 189, in parse_values_from_connection_kwargs
    return convert(kwargs, cls, strict=False, dec_hook=deserializer, str_keys=True).to_dict()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
msgspec.ValidationError: Expected `array`, got `UploadFile` - at `$.data.files`

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/guacs/open-source/litestar/litestar/middleware/exceptions/middleware.py", line 191, in __call__
    await self.app(scope, receive, send)
  File "/home/guacs/open-source/litestar/litestar/routes/http.py", line 82, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guacs/open-source/litestar/litestar/routes/http.py", line 134, in _get_response_for_request
    return await self._call_handler_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guacs/open-source/litestar/litestar/routes/http.py", line 154, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guacs/open-source/litestar/litestar/routes/http.py", line 193, in _get_response_data
    parsed_kwargs = route_handler.signature_model.parse_values_from_connection_kwargs(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guacs/open-source/litestar/litestar/_signature/model.py", line 202, in parse_values_from_connection_kwargs
    raise cls._create_exception(messages=messages, connection=connection) from e
litestar.exceptions.http_exceptions.ValidationException: 400: Validation failed for POST http://testserver.local/
```

### Litestar Version

HEAD

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2939">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2939/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2939/pledge.svg">
</picture>
</a>

**Comment by guacs** [comment] 2024-01-03 08:00
Actually, I don't think this is a bug. This is not what the usage is meant to be I believe. The attributes on the defined model should be the filenames which means a list of files would not be an appropriate annotation. That being said, if this is the case, then the following does not work either:

```python

from __future__ import annotations

from msgspec import Struct

from litestar import post
from litestar.datastructures import UploadFile
from litestar.enums import RequestEncodingType
from litestar.params import Body
from litestar.status_codes import HTTP_201_CREATED
from litestar.testing.helpers import create_test_client


class Form(Struct):
    cv: UploadFile
    diploma: UploadFile


@post(path="/")
async def upload_files_object(data: Form = Body(media_type=RequestEncodingType.MULTI_PART)) -> list[str]:
    return [data.cv.filename, data.diploma.filename]


with create_test_client([upload_files_object]) as client:
    files = [("files", ("cv", b"1")), ("files", ("diploma", b"1"))]
    response = client.post("/", files=files)

    assert response.status_code == HTTP_201_CREATED
    assert response.json() == ["cv", "diploma"]
```

In the example above, the field name will be `files` whereas the filenames will be `cv` and `diploma`. @litestar-org/members, can someone confirm the following:

- whether this issue is a bug or not
- whether the example in this comment not working is the actual bug

**Comment by provinzkraut** [comment] 2024-01-03 17:58
Thanks for the investigation @guacs!

I don't think this is a bug. I think neither usage is intended to be supported at the moment.

The correct way to annotate the example given would be

```python

class Files(Struct):
    cv: UploadFile
    diploma: UploadFile

class Form(Struct):
    files: Files


@post(path="/")
async def upload_files_object(data: Form = Body(media_type=RequestEncodingType.MULTI_PART)) -> list[str]:
    return [data.files.cv.filename, data.files.diploma.filename]


with create_test_client([upload_files_object]) as client:
    files = [("files", ("cv", b"1")), ("files", ("diploma", b"1"))]
    response = client.post("/", files=files)
``` 
to take into account the actual field name as well.

To support this, we'd generally have to support nested data structures for multipart uploads, which is something we could do, but we'd have to change quite a few things for this to work.

Personally, I think the current level of support is "good enough"; Being able to validate filenames like this via the signature validation would be a rather fundamental change.

Closing this for now as it's not a bug. If there's interest, we can reopen this as a feature request in the future.

**Comment by guacs** [comment] 2024-01-04 03:21
@provinzkraut so to confirm, you're saying the following example should is not supported:

```python
from __future__ import annotations

from msgspec import Struct

from litestar import post
from litestar.datastructures import UploadFile
from litestar.enums import RequestEncodingType
from litestar.params import Body
from litestar.status_codes import HTTP_201_CREATED
from litestar.testing.helpers import create_test_client


class Form(Struct):
    cv: UploadFile
    diploma: UploadFile


@post(path="/")
async def upload_files_object(data: Form = Body(media_type=RequestEncodingType.MULTI_PART)) -> list[str]:
    return [data.cv.filename, data.diploma.filename]


with create_test_client([upload_files_object]) as client:
    files = [("files", ("cv", b"1")), ("files", ("diploma", b"1"))]
    response = client.post("/", files=files)

    assert response.status_code == HTTP_201_CREATED
    assert response.json() == ["cv", "diploma"]
```

If so, then I think either we have to add support for it or clarify the documentation regarding it because as per the [docs](https://docs.litestar.dev/2/usage/requests.html#multiple-files), the above code should work.

**Comment by provinzkraut** [comment] 2024-01-04 15:12
Reading the docs again, I think what's expected there as the request data is actually something like 

```python
with create_test_client([upload_files_object]) as client:
    files = [("cv", b"1"), ("diploma", b"1")]
    response = client.post("/", files=files)
```

So you don't have the nested structure, but simply a multipart body with multiple files in it. The line "multiple named files" is misleading I think.

**Comment by guacs** [comment] 2024-01-05 04:07
> Reading the docs again, I think what's expected there as the request data is actually something like
> 
> ```python
> with create_test_client([upload_files_object]) as client:
>     files = [("cv", b"1"), ("diploma", b"1")]
>     response = client.post("/", files=files)
> ```
> 
> So you don't have the nested structure, but simply a multipart body with multiple files in it. The line "multiple named files" is misleading I think.

Aah that make sense to me. Yeah, it was the "multiple named files" that got me confused.

**Comment by guacs** [comment] 2024-01-05 04:11
Actually, @provinzkraut why isn't the example shown in the original MCVE supported? It's possible that only a single file is given for a single field name in the multipart form, no? So, I'd argue that the original bug I'd mentioned is actually a bug.

**Closed** 2024-01-05 14:45 UTC
Labels: Bug :bug:
