### ISSUE TITLE
Enhancement: Pydantic models, dataclasses or msgpack structs as query, header or cookie

### ISSUE THREAD

**Issue by Forceres** [litestar-org/litestar#3841] opened 2024-10-26 21:12 UTC
### Summary

FastAPI has recently announced new feature with Pydantic models support for Query, Header or Cookie.
So, I guess it could be possible to implement something like that in Litestar.

### Basic Example

class FilterParams(BaseModel):
    limit: int = Field(100, gt=0, le=100)
    offset: int = Field(0, ge=0)
    order_by: Literal["created_at", "updated_at"] = "created_at"
    tags: list[str] = []

@get("/items/")
async def read_items(filter_query: Annotated[FilterParams, Query()]):
    return filter_query

### Drawbacks and Impact

I am sure that it could be a silver bullet for discarding a lot of unnecessary codebase with explicitly specifying all types of params.

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3841">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3841/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3841/pledge.svg">
</picture>
</a>

**Comment by Alc-Alc** [comment] 2024-10-27 01:59
Duplicate of https://github.com/litestar-org/litestar/issues/2015

**Closed by Alc-Alc** 2024-10-27 01:59 UTC
Labels: Enhancement
