### ISSUE TITLE
Bug: `Request.url.scheme` doesn't match `scope['scheme']`

### ISSUE THREAD

**Issue by trim21** [litestar-org/litestar#3707] opened 2024-08-25 19:33 UTC
### Description

uvicorn have a  `--proxy-headers` flag to handle common proxy header like [X-Forwarded-Proto](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto), and it change `scope['scheme']` to https for proxied https request.

But request.url.scheme are always http in this case, doesn't match real client url.

### MCVE

```python
server code:

import litestar


@litestar.get("/", sync_to_thread=False)
def handle(request: litestar.Request) -> str:
    return str(request.url)


app = litestar.Litestar([handle])


# run server with `uvicorn --proxy-headers`
client code :

```python
import httpx


r = httpx.get("http://127.0.0.1:8000/", headers={"X-Forwarded-Proto": "https"})

print(r.text)
```
```


### Steps to reproduce

```bash
1. copy server code
2. copy client code
3. `uvicorn --proxy-headers`
4. run client
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

2.10.0

### Platform

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [X] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3707">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3707/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3707/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment] 2024-08-25 19:35
Duplicate of #3706.

**Closed by provinzkraut** 2024-08-25 19:35 UTC
Labels: Bug :bug:
