### ISSUE TITLE
Enhancment: Support mounting WSGI apps

### ISSUE THREAD

**Issue by provinzkraut** [litestar-org/litestar#707] opened 2022-10-29 17:36 UTC
**What's the feature you'd like to ask for.**

In the wake of #681/#694, support for mounting WSGI applications would be really good to have as well.

```python
from starlite import Starlite, wsgi
from wsgi import application

app = Starlite(route_handlers=[wsgi("/wsgi-path", is_mount=True)])
```

**Comment by provinzkraut** [comment] 2022-11-11 11:34
I started looking into this, and there's the [a2wsgi](https://github.com/abersheeran/a2wsgi) package, which seems like a sound solution to me, and it addresses a few common problems with WSGI wrappers found in other libraries. We could include it as an optional dependency. 

The only issue with it is that it currently doesn't support `anyio`, which means it's not suitable for us. They have expressed their interest in moving to `anyio` though, so it might be worth contributing to that on their side so we can integrate it.

The alternative would be to roll our own, which would have some advantages (`anyio`-compatible right away, less external dependencies, fit for purpose), but I think this would be outweighed by the downsides, mainly more things to maintain for us, and needlessly adding code that already exists somewhere else.

**Comment by Goldziher** [comment] 2022-12-01 18:06
So, the question is whether there is actually a good use case for this? I cannot see under what circumstances doing this would be good thing to be honest. And for those who really do need this functionality, they can pretty easily implement it with `a2wsgi` package you link to above. I would suggest we close this one. Leaving it to your discretion though @provinzkraut - im not touching this 😉

**Comment by provinzkraut** [comment] 2022-12-02 13:02
I think the use case is mostly easily integrating legacy apps. Of course we can point to third party tools, but that's true for many things. I agree that it's not necessary for us to integrate this, but it's a nice convenience option to have. 

I've had a working implementation for this ready for a while now, based on `a2wsgi`. I just didn't get around to finishing it up. Let's keep this open for now, and if I get to it, I get to it, and if I don't, well, as you said, it's probably not a critical feature ;)

**Comment by byzantic** [comment] 2023-04-28 12:33
I can think of one usecase that I am currently looking at. I would like to use Litestar as the service layer for my application, but there is an existing application that must be incorporated, which is built with dash (which itself is built on Flask)

There is a way of doing this with FastAPI, which is documented here:

https://github.com/rusnyder/fastapi-plotly-dash

**Comment by provinzkraut** [comment] 2023-04-28 13:04
@byzantic This approach uses the deprecated `WSGIMiddleware` from starlette. The currently recommended way to do this in FastAPI is to use the [a2wsgi](https://github.com/abersheeran/a2wsgi) package, which works for Litestar as well.

**Comment by byzantic** [comment] 2023-04-28 13:13
Thanks!

**Comment by JacobCoffee** [comment] 2023-05-01 00:23
[a2wsgi](https://github.com/abersheeran/a2wsgi) is the answer here.

**Closed by JacobCoffee** 2023-05-01 00:23 UTC
Labels: enhancement

**Comment by Matteomt** [comment] 2024-08-28 11:46
> [a2wsgi](https://github.com/abersheeran/a2wsgi) is the answer here.

It does not work anymore for me.
I think the issue is since v2.7.0 after commit https://github.com/litestar-org/litestar/commit/e15b93d8d0ef1b92b9127bd771630bcf78352bf2 that introduced more usage of deepcopy. I questioned the approach here: https://github.com/orgs/litestar-org/discussions/3711

My current workaround is to patch `WSGIMiddleware` from `a2wsgi` as follows:
```python
class _NoCopyWSGIMiddleware(WSGIMiddleware):
    def __copy__(self):
        return self
    def __deepcopy__(self, memo=None):
        return self
```
