### ISSUE TITLE
Docs: Example Image Backgrounds

### ISSUE THREAD

**Issue by therealzanfar** [litestar-org/litestar#2053] opened 2023-07-23 18:19 UTC
### Summary

Many images in the documentation appear to have a transparent background. This works well when the page background is white--which I assume is the default. However, these images become partially unreadable when the page background is dark--most commonly caused by switching to the "dark" theme in the documentation website. This is exasperated by the fact that the documentation site appears to inherit the theme of the browser.

Specific example:
https://docs.litestar.dev/2/usage/dto/index.html

The lane transition text is almost invisible in dark mode.

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2053">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2053/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2053/pledge.svg">
</picture>
</a>

**Comment by Goldziher** [comment] 2023-07-23 18:23
PR welcome

**Comment by provinzkraut** [comment] 2023-07-23 18:30
Duplicate of #1687.

This is an issue with mermaid (which we use to generate those graphics) apparently being quite difficult to adjust to a dark theme.

We still ought to figure out a solution to that one.

**Closed by provinzkraut** 2023-07-23 18:30 UTC
Labels: documentation

**Comment by therealzanfar** [comment] 2023-07-23 18:31
Re: @Goldziher I'd love to. Unfortunately, I'm not familiar enough with your doc generation tools to produce on at this time. I am, however, looking into it.

It appears to be a parameter of the `sphinxcontrib-mermaid` extension that controls this. However, the default is documented as a white background, and I do not see any config that overrides this, so I'm not sure how the transparent background is being specified.

@provinzkraut Sorry for the duplicate, I'll contribute there if possible.

**Comment by Goldziher** [comment] 2023-07-23 19:01
> Duplicate of #1687.
> 
> This is an issue with mermaid (which we use to generate those graphics) apparently being quite difficult to adjust to a dark theme.
> 
> We still ought to figure out a solution to that one. 

We can override the css with deep selectors,

**Comment by therealzanfar** [comment] 2023-07-23 19:04
> We can override the css with deep selectors. Does sphinx set a css variable for the theme? If so it's easy to do.

https://github.com/litestar-org/litestar/issues/1687#issuecomment-1646928039

It's not clear to me if this change should be made in this project, or litestar-org/litestar-sphinx-theme, but I'm happy to attempt a PR in either.
